# Generated by Django 4.2.11 on 2026-04-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_service_image_and_seed_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='mobile_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
